# Generated by Django 4.1.1 on 2022-10-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="is_staff",),
    ]
