# Generated by Django 4.1.1 on 2022-10-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_account_is_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
