# Generated by Django 4.1.1 on 2022-10-10 05:59

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Category Name"),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Category Slug"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "category_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_icons"
                    ),
                ),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="category_images",
                        verbose_name="Category Image",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CategorySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Category Section Name"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_section",
                        to="category.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category section",
                "verbose_name_plural": "category sections",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Subcategory Name"),
                ),
                (
                    "slug",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Subcategory Slug"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="status")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_category",
                        to="category.category",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sec_sub_category",
                        to="category.categorysection",
                    ),
                ),
            ],
            options={
                "verbose_name": "subcategory",
                "verbose_name_plural": "subcategories",
                "ordering": ("name",),
            },
        ),
    ]
