# Generated by Django 4.1.1 on 2022-10-01 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='image',
            new_name='upload_image',
        ),
    ]
